variable "vpc_cidr" {}
variable "public_subnet_cidr" {}
variable "private_subnet_cidr" {}
variable "azs" {}
variable "route_cidr" {}
variable "security_group_name" {}
variable "description" {}
variable "vpc_tag" {}
variable "lb_sg_id" {}