variable "lb_name" {}
variable "lb_subnet_id" {}
variable "lb_type" {}
variable "lb_tag" {}
variable "lb_tg_name" {}
variable "lb_protocol" {}
variable "lb_tg_tag" {}
variable "lb_lst_type" {}
variable "lb_vpc_id" {}
variable "lb_subnet_id_1" {}
